-- Generated by matugen - do not edit manually

colors = {
    font  = "Iosevka Term",
    image = "{{image}}",
<* for name, value in colors *>
    {{name}} = "rgba({{value.default.hex_stripped}}ff)",
<* endfor *>
}
