-- https://wiki.hypr.land/Configuring/Basics/Autostart/
hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user enable --now hyprpaper.service")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 24")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("pypr")
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("openrgb --server")
    hl.exec_cmd("streamdeck")
    hl.exec_cmd("ghostty --gtk-single-instance=true --quit-after-last-window-closed=false --initial-window=false")
    hl.exec_cmd("foot -s")
    hl.exec_cmd("sh -c 'wl-paste --watch cliphist store'")
end)
